# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'Company' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!
    pod 'SDWebImage', '~>3.7'
    pod 'MBProgressHUD'
    pod 'AFNetworking', '~> 3.0'
    pod 'PNChart'
    pod 'FDFullscreenPopGesture', '1.1'

  # Pods for Company

end
